name: GitHub Lineage Mirror Build GKI5.10
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install system dependencies
        run: |
         sudo apt update -y
         sudo apt install -y git make ccache zip unzip bc libssl-dev coreutils

      - name: Download Clang r416183b (Lineage GitHub Mirror)
        run: git clone --depth=1 https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b clang-r416183b

      - name: Download aarch64 GCC4.9 (Lineage GitHub Mirror)
        run: git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 gcc-aarch64

      - name: Download arm GCC4.9 (Lineage GitHub Mirror)
        run: git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 gcc-arm

      - name: Clone AnyKernel3
        run: git clone --depth=1 https://github.com/osm0sis/AnyKernel3 ak3

      # 缓存步骤移至工具链全部下载完毕后，首次构建可正常缓存工具链
      - name: Cache Toolchain
        uses: actions/cache@v4
        with:
          path: |
            clang-r416183b
            gcc-aarch64
            gcc-arm
          key: toolchain-r416183b

      - name: Build Kernel (Lineage Mirror Toolchain)
        env:
          ARCH: arm64
          SUBARCH: arm64
          KD: gki_defconfig
          PATH: ${{ github.workspace }}/clang-r416183b/bin:${{ github.workspace }}/gcc-aarch64/bin:${{ github.workspace }}/gcc-arm/bin:$PATH
        run: |
          ARGS="-j16 ARCH=arm64 SUBARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu-"
          
          make clean && make mrproper
          rm -rf out && mkdir -p out
          
          make CC="ccache clang" $ARGS $KD
          make CC="ccache clang" $ARGS olddefconfig
          make CC="ccache clang" $ARGS prepare
          make CC="ccache clang" $ARGS 2>&1 | tee kernel_build.log

      - name: Package & Slim AnyKernel Zip
        run: |
          cp out/arch/arm64/boot/Image ak3/
          cd ak3
          rm -rf tools/lptools_static tools/htools_static modules/system/lib/placeholder patch ramdisk
          zip -r -9 kernel-$(git rev-parse --short HEAD).zip .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GKI5.10-GitHubMirror-${{ github.sha }}
          path: |
            ak3/*.zip
            kernel_build.log
